name: Main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  api_key_approach:
    runs-on: windows-latest
    name: API Key Authentication Example
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get AAD Secret
        id: aad-secret
        uses: ./
        with:
          akeyless-secret-path: '/DevTools/live-azure-ad'
          akeyless-access-id: 'p-m9vvgiii6rip'
          akeyless-access-key: '${{ secrets.AKEYLESS_ACCESS_KEY }}'

      - name: Verify Output
        shell: pwsh
        run: |
          echo "${{ steps.aad-secret.outputs.app-id }}"
          echo "${{ steps.aad-secret.outputs.tenant-id }}"
          echo "${{ steps.aad-secret.outputs.secret-text }}"
          echo "${{ steps.aad-secret.outputs.key-id }}"
          echo "${{ steps.aad-secret.outputs.display-name }}"

  jwt_approach:
    runs-on: windows-latest
    name: JWT Authentication Example

    # Required for JWT authentication
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get AAD Secret
        id: aad-secret
        uses: ./
        with:
          akeyless-secret-path: '/DevTools/live-azure-ad'
          akeyless-access-id: 'p-149l6gayzx05'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Output
        shell: pwsh
        run: |
          echo "${{ steps.aad-secret.outputs.app-id }}"
          echo "${{ steps.aad-secret.outputs.tenant-id }}"
          echo "${{ steps.aad-secret.outputs.secret-text }}"
          echo "${{ steps.aad-secret.outputs.key-id }}"
          echo "${{ steps.aad-secret.outputs.display-name }}"